### ISSUE TITLE
[ezfix] Ore Dict Registration Errors

### ISSUE THREAD

**Issue by T145** [Shadows-of-Fire/FastWorkbench#17]
Just got some of these:
```
[00:06:12] [Client thread/WARN] [FML]: ****************************************
[00:06:12] [Client thread/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name workbench has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[00:06:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:665)
[00:06:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[00:06:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:650)
[00:06:12] [Client thread/WARN] [FML]: *  at shadows.fastbench.FastBench.init(FastBench.java:84)
[00:06:12] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:06:12] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
[00:06:12] [Client thread/WARN] [FML]: ****************************************
[00:06:12] [Client thread/WARN] [FML]: ****************************************
[00:06:12] [Client thread/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name craftingTableWood has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[00:06:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:665)
[00:06:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[00:06:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:650)
[00:06:12] [Client thread/WARN] [FML]: *  at shadows.fastbench.FastBench.init(FastBench.java:85)
[00:06:12] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:06:12] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
[00:06:12] [Client thread/WARN] [FML]: ****************************************
```

Slap the oredict registration in a:
```java
@SubscribeEvent(priority = EventPriority.HIGHEST)
public static void registerRecipes(RegistryEvent.Register<IRecipe> event) { ... }
```
method to fix it.

**Comment by Shadows-of-Fire** [comment]
I need to look into what propagates that error message.
The timing of when the registration fires is irrelevant for causing such an error, so something else is happening.  I think that's what shows up when an empty stack is attempted to be registered, so that would mean something else is replacing the crafting table after me.

**Comment by Shadows-of-Fire** [comment]
Yeah this is caused by someone else replacing the table after me or someone else causing my replacement to fail.  Anyway, such a mod is incompatible with FB, and there's no way around it.
